name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build Docker image
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-510715/notely-ar-repo/notely:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-510715/notely-ar-repo/notely@sha256:eb04d00d957f99c64e3156f8f47d77bef8e5672e9ffcca1ba30fd9d1feb407a7 --region us-central1 --allow-unauthenticated --project notely-510715 --max-instances=4
